### ISSUE TITLE
赞一个！

### ISSUE THREAD

**Issue by lyfoppa** [liungkejin/Bash-Games#1]
另外想问问作者，那个屏保可以做成mac屏保吗

**Comment by liungkejin** [comment]
因为 mac 默认的 bash 为 GNU bash 3.2, 不支持 sleep 0.1 , read -t 0.1 这种低于1s的参数，除了 clocksaver.sh，translate.sh 这个命令，其他脚本只要把 bash 升级到 4.x 版本就可以正常使用
aclock.sh 这个脚本我刚刚修改好可以适配 bash 3.2 了
如果要使用 clocksaver.sh 的话，还需要一个 logkey 这个工具命令，这个我在 mac 上没有找到，所以你需要更换其他工具来实现，或者换其他思路来实现

**Comment by JackMerlin** [comment]
借 issues 提一个问题。

@liungkejin 非常感谢您打造了这些有趣的脚本，请问是使用什么许可证发布的 Tetris 和 Snake？我想将您的代码嵌入我的脚本中，作为一个小彩蛋，[我的项目](https://github.com/JackMerlin/USBAccelerator)是使用 GPLv3。
您是否同意呢？当然我会全部保留您的版权信息，并严格尊重您提出的要求。
这里有些顾虑主要就是如果您同意，担心您的许可证不知是否和我的兼容。

**Comment by liungkejin** [comment]
@JackMerlin  随便用~ 哈哈

**Comment by JackMerlin** [comment]
@liungkejin 
> 随便用~ 哈哈


非常感谢。
